name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Test tap
        run: |
          brew tap RhetTbull/osxphotos
          brew install --build-from-source RhetTbull/osxphotos/osxphotos
          osxphotos --version
          osxphotos --help

      - name: Test bitstring works without tibs Rust extension
        run: |
          "$(brew --prefix osxphotos)/libexec/bin/python" -c "import bitstring; bitstring.BitArray(uint=1, length=8)"
